language: node_js
node_js:
  - 6
install:
  - npm install
  - npm install -g codecov
cache:
  directories:
    - node_modules
script:
  - npm test -- --coverage && codecov
# removed due to build issues with travis --- Out of Memory?!
#  - npm run build
after-success:
  - bash <(curl -s https://codecov.io/bash)